helm:
  parameters:
  - name: image.name
    value: andreistefanciprian/urlshortener-frontend
    forcestring: true
  - name: image.tag
    value: latest@sha256:dbfcad371bd0be9e12279ac80426aa1014513434dc09f2e859db32d0e458a532
    forcestring: true
