services:

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: infra/Dockerfile
  #   ports:
  #     - "8090:8090"
  #   environment:
  #     - BACKEND_HOST=api-gateway
  #     - BACKEND_PORT=8080
  #     - FRONTEND_PORT=8090
  #     - LOG_LEVEL=DEBUG
  #   depends_on:
  #     api-gateway:
  #       condition: service_started
  #   networks:
  #     - urlshortener

  frontend2:
    build:
      context: ./frontend2
      dockerfile: infra/Dockerfile
    ports:
      - "8091:8091"
    environment:
      - BACKEND_HOST=api-gateway
      - BACKEND_PORT=8080
      - FRONTEND_PORT=8091
      - LOG_LEVEL=DEBUG
    depends_on:
      api-gateway:
        condition: service_started
    networks:
      - urlshortener

  # API Gateway - HTTP Server
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: infra/Dockerfile
    ports:
      - "80:8080"
      - "9090:9090"
      - "3000:3000"
    environment:
      - URL_GEN_HOST=url-gen
      - URL_GEN_PORT=50052
      - URL_READ_HOST=url-read
      - URL_READ_PORT=50053
      - API_GATEWAY_PORT=8080
      - METRICS_PORT=9090
      - LOG_LEVEL=DEBUG
      - URL_SCHEME=http
    depends_on:
      url-gen:
        condition: service_started
    networks:
      - urlshortener

  # URL Generation Service - gRPC Server
  url-gen:
    build:
      context: ./url-gen
      dockerfile: infra/Dockerfile
    ports:
      - "50052:50052"
    environment:
      - DB_HOST=url-gen-db
      - DB_PORT=5432
      - DB_NAME=urls
      - DB_USER=url_gen_user
      - DB_PASSWORD=Auth123
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redispassword
      - REDIS_DB=0
      - URL_GEN_PORT=50052
      - GRPC_REFLECTION=true
      - LOG_LEVEL=DEBUG
    depends_on:
      url-gen-db:
        condition: service_healthy
        restart: true
    networks:
      - urlshortener

  # URL Reading Service - gRPC Server
  url-read:
    build:
      context: ./url-read
      dockerfile: infra/Dockerfile
    ports:
      - "50053:50053"
    environment:
      - DB_HOST=url-gen-db
      - DB_PORT=5432
      - DB_NAME=urls
      - DB_USER=url_read_user
      - DB_PASSWORD=Auth123
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redispassword
      - REDIS_DB=0
      - URL_READ_PORT=50053
      - GRPC_REFLECTION=true
      - LOG_LEVEL=DEBUG
    depends_on:
      url-gen-db:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy
        restart: true
    networks:
      - urlshortener  

  # PostgreSQL Database - url-gen-db
  url-gen-db:
    image: postgres:15-alpine
    container_name: url-gen-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - urlshortener
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Redis Cache
  redis:
    image: redis:8-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass redispassword
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redispassword", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - urlshortener

volumes:
  postgres_data:
  redis_data:

networks:
  urlshortener:
    driver: bridge