apiVersion: v1
kind: Secret
metadata:
  name: {{ include "url-gen.fullname" . }}-secret
  labels:
    {{- include "url-gen.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD | b64enc }}