image:
  repository: andreistefanciprian/urlshortener-url-read
  digest: sha256:1bf153e3080fd810878f44ef7cd04461c05f3c9046cac732e659f96eab45c96a
  tag: latest

config:
  LOG_LEVEL: DEBUG
  DB_HOST: postgres-postgresql.postgres.svc
  REDIS_HOST: redis-master.redis.svc
  DB_USER: url_gen_user
  REDIS_DB: "0"
