image:
  repository: andreistefanciprian/urlshortener-url-gen
  digest: sha256:bd964b5f5b233001a775bce1064d9ebc5171d6d3db73e77c0cc2d4c52d227023
  tag: latest

config:
  LOG_LEVEL: DEBUG
  DB_HOST: postgres-postgresql.postgres.svc
  DB_USER: url_gen_user
  REDIS_HOST: redis-master.redis.svc
  REDIS_DB: "0"
