// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.23.4
// source: url-gen/proto/url-gen.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LongUrl       string                 `protobuf:"bytes,1,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	Expiration    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expiration,proto3" json:"expiration,omitempty"` // Optional expiration date
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortURLRequest) Reset() {
	*x = ShortURLRequest{}
	mi := &file_url_gen_proto_url_gen_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURLRequest) ProtoMessage() {}

func (x *ShortURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_gen_proto_url_gen_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortURLRequest.ProtoReflect.Descriptor instead.
func (*ShortURLRequest) Descriptor() ([]byte, []int) {
	return file_url_gen_proto_url_gen_proto_rawDescGZIP(), []int{0}
}

func (x *ShortURLRequest) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

func (x *ShortURLRequest) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

type ShortURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortURLResponse) Reset() {
	*x = ShortURLResponse{}
	mi := &file_url_gen_proto_url_gen_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURLResponse) ProtoMessage() {}

func (x *ShortURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_gen_proto_url_gen_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortURLResponse.ProtoReflect.Descriptor instead.
func (*ShortURLResponse) Descriptor() ([]byte, []int) {
	return file_url_gen_proto_url_gen_proto_rawDescGZIP(), []int{1}
}

func (x *ShortURLResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type DeleteShortURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrlCode  string                 `protobuf:"bytes,1,opt,name=short_url_code,json=shortUrlCode,proto3" json:"short_url_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShortURLRequest) Reset() {
	*x = DeleteShortURLRequest{}
	mi := &file_url_gen_proto_url_gen_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShortURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShortURLRequest) ProtoMessage() {}

func (x *DeleteShortURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_gen_proto_url_gen_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShortURLRequest.ProtoReflect.Descriptor instead.
func (*DeleteShortURLRequest) Descriptor() ([]byte, []int) {
	return file_url_gen_proto_url_gen_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteShortURLRequest) GetShortUrlCode() string {
	if x != nil {
		return x.ShortUrlCode
	}
	return ""
}

type DeleteShortURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Optional message for additional context
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShortURLResponse) Reset() {
	*x = DeleteShortURLResponse{}
	mi := &file_url_gen_proto_url_gen_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShortURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShortURLResponse) ProtoMessage() {}

func (x *DeleteShortURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_gen_proto_url_gen_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShortURLResponse.ProtoReflect.Descriptor instead.
func (*DeleteShortURLResponse) Descriptor() ([]byte, []int) {
	return file_url_gen_proto_url_gen_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteShortURLResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteShortURLResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type URLRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	ShortUrlCode  string                 `protobuf:"bytes,2,opt,name=short_url_code,json=shortUrlCode,proto3" json:"short_url_code,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpireTime    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"` // Optional expiration date
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLRecord) Reset() {
	*x = URLRecord{}
	mi := &file_url_gen_proto_url_gen_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLRecord) ProtoMessage() {}

func (x *URLRecord) ProtoReflect() protoreflect.Message {
	mi := &file_url_gen_proto_url_gen_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLRecord.ProtoReflect.Descriptor instead.
func (*URLRecord) Descriptor() ([]byte, []int) {
	return file_url_gen_proto_url_gen_proto_rawDescGZIP(), []int{4}
}

func (x *URLRecord) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *URLRecord) GetShortUrlCode() string {
	if x != nil {
		return x.ShortUrlCode
	}
	return ""
}

func (x *URLRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *URLRecord) GetExpireTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireTime
	}
	return nil
}

type GetAllURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*URLRecord           `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllURLsResponse) Reset() {
	*x = GetAllURLsResponse{}
	mi := &file_url_gen_proto_url_gen_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllURLsResponse) ProtoMessage() {}

func (x *GetAllURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_gen_proto_url_gen_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllURLsResponse.ProtoReflect.Descriptor instead.
func (*GetAllURLsResponse) Descriptor() ([]byte, []int) {
	return file_url_gen_proto_url_gen_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllURLsResponse) GetUrls() []*URLRecord {
	if x != nil {
		return x.Urls
	}
	return nil
}

var File_url_gen_proto_url_gen_proto protoreflect.FileDescriptor

const file_url_gen_proto_url_gen_proto_rawDesc = "" +
	"\n" +
	"\x1burl-gen/proto/url-gen.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"h\n" +
	"\x0fShortURLRequest\x12\x19\n" +
	"\blong_url\x18\x01 \x01(\tR\alongUrl\x12:\n" +
	"\n" +
	"expiration\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiration\"/\n" +
	"\x10ShortURLResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\"=\n" +
	"\x15DeleteShortURLRequest\x12$\n" +
	"\x0eshort_url_code\x18\x01 \x01(\tR\fshortUrlCode\"L\n" +
	"\x16DeleteShortURLResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xcc\x01\n" +
	"\tURLRecord\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\x12$\n" +
	"\x0eshort_url_code\x18\x02 \x01(\tR\fshortUrlCode\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vexpire_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expireTime\"4\n" +
	"\x12GetAllURLsResponse\x12\x1e\n" +
	"\x04urls\x18\x01 \x03(\v2\n" +
	".URLRecordR\x04urls2\xc5\x01\n" +
	"\fURLGenerator\x127\n" +
	"\x10GenerateShortURL\x12\x10.ShortURLRequest\x1a\x11.ShortURLResponse\x12A\n" +
	"\x0eDeleteShortURL\x12\x16.DeleteShortURLRequest\x1a\x17.DeleteShortURLResponse\x129\n" +
	"\n" +
	"GetAllURLs\x12\x16.google.protobuf.Empty\x1a\x13.GetAllURLsResponseB;Z9github.com/andreistefanciprian/urlshortener/url-gen/protob\x06proto3"

var (
	file_url_gen_proto_url_gen_proto_rawDescOnce sync.Once
	file_url_gen_proto_url_gen_proto_rawDescData []byte
)

func file_url_gen_proto_url_gen_proto_rawDescGZIP() []byte {
	file_url_gen_proto_url_gen_proto_rawDescOnce.Do(func() {
		file_url_gen_proto_url_gen_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_url_gen_proto_url_gen_proto_rawDesc), len(file_url_gen_proto_url_gen_proto_rawDesc)))
	})
	return file_url_gen_proto_url_gen_proto_rawDescData
}

var file_url_gen_proto_url_gen_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_url_gen_proto_url_gen_proto_goTypes = []any{
	(*ShortURLRequest)(nil),        // 0: ShortURLRequest
	(*ShortURLResponse)(nil),       // 1: ShortURLResponse
	(*DeleteShortURLRequest)(nil),  // 2: DeleteShortURLRequest
	(*DeleteShortURLResponse)(nil), // 3: DeleteShortURLResponse
	(*URLRecord)(nil),              // 4: URLRecord
	(*GetAllURLsResponse)(nil),     // 5: GetAllURLsResponse
	(*timestamppb.Timestamp)(nil),  // 6: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),          // 7: google.protobuf.Empty
}
var file_url_gen_proto_url_gen_proto_depIdxs = []int32{
	6, // 0: ShortURLRequest.expiration:type_name -> google.protobuf.Timestamp
	6, // 1: URLRecord.created_at:type_name -> google.protobuf.Timestamp
	6, // 2: URLRecord.expire_time:type_name -> google.protobuf.Timestamp
	4, // 3: GetAllURLsResponse.urls:type_name -> URLRecord
	0, // 4: URLGenerator.GenerateShortURL:input_type -> ShortURLRequest
	2, // 5: URLGenerator.DeleteShortURL:input_type -> DeleteShortURLRequest
	7, // 6: URLGenerator.GetAllURLs:input_type -> google.protobuf.Empty
	1, // 7: URLGenerator.GenerateShortURL:output_type -> ShortURLResponse
	3, // 8: URLGenerator.DeleteShortURL:output_type -> DeleteShortURLResponse
	5, // 9: URLGenerator.GetAllURLs:output_type -> GetAllURLsResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_url_gen_proto_url_gen_proto_init() }
func file_url_gen_proto_url_gen_proto_init() {
	if File_url_gen_proto_url_gen_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_url_gen_proto_url_gen_proto_rawDesc), len(file_url_gen_proto_url_gen_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_url_gen_proto_url_gen_proto_goTypes,
		DependencyIndexes: file_url_gen_proto_url_gen_proto_depIdxs,
		MessageInfos:      file_url_gen_proto_url_gen_proto_msgTypes,
	}.Build()
	File_url_gen_proto_url_gen_proto = out.File
	file_url_gen_proto_url_gen_proto_goTypes = nil
	file_url_gen_proto_url_gen_proto_depIdxs = nil
}
