// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.23.4
// source: url-gen/proto/url-gen.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	URLGenerator_GenerateShortURL_FullMethodName = "/URLGenerator/GenerateShortURL"
	URLGenerator_DeleteShortURL_FullMethodName   = "/URLGenerator/DeleteShortURL"
	URLGenerator_GetAllURLs_FullMethodName       = "/URLGenerator/GetAllURLs"
)

// URLGeneratorClient is the client API for URLGenerator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type URLGeneratorClient interface {
	GenerateShortURL(ctx context.Context, in *ShortURLRequest, opts ...grpc.CallOption) (*ShortURLResponse, error)
	DeleteShortURL(ctx context.Context, in *DeleteShortURLRequest, opts ...grpc.CallOption) (*DeleteShortURLResponse, error)
	GetAllURLs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAllURLsResponse, error)
}

type uRLGeneratorClient struct {
	cc grpc.ClientConnInterface
}

func NewURLGeneratorClient(cc grpc.ClientConnInterface) URLGeneratorClient {
	return &uRLGeneratorClient{cc}
}

func (c *uRLGeneratorClient) GenerateShortURL(ctx context.Context, in *ShortURLRequest, opts ...grpc.CallOption) (*ShortURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShortURLResponse)
	err := c.cc.Invoke(ctx, URLGenerator_GenerateShortURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uRLGeneratorClient) DeleteShortURL(ctx context.Context, in *DeleteShortURLRequest, opts ...grpc.CallOption) (*DeleteShortURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteShortURLResponse)
	err := c.cc.Invoke(ctx, URLGenerator_DeleteShortURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uRLGeneratorClient) GetAllURLs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAllURLsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllURLsResponse)
	err := c.cc.Invoke(ctx, URLGenerator_GetAllURLs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// URLGeneratorServer is the server API for URLGenerator service.
// All implementations must embed UnimplementedURLGeneratorServer
// for forward compatibility.
type URLGeneratorServer interface {
	GenerateShortURL(context.Context, *ShortURLRequest) (*ShortURLResponse, error)
	DeleteShortURL(context.Context, *DeleteShortURLRequest) (*DeleteShortURLResponse, error)
	GetAllURLs(context.Context, *emptypb.Empty) (*GetAllURLsResponse, error)
	mustEmbedUnimplementedURLGeneratorServer()
}

// UnimplementedURLGeneratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedURLGeneratorServer struct{}

func (UnimplementedURLGeneratorServer) GenerateShortURL(context.Context, *ShortURLRequest) (*ShortURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateShortURL not implemented")
}
func (UnimplementedURLGeneratorServer) DeleteShortURL(context.Context, *DeleteShortURLRequest) (*DeleteShortURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteShortURL not implemented")
}
func (UnimplementedURLGeneratorServer) GetAllURLs(context.Context, *emptypb.Empty) (*GetAllURLsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllURLs not implemented")
}
func (UnimplementedURLGeneratorServer) mustEmbedUnimplementedURLGeneratorServer() {}
func (UnimplementedURLGeneratorServer) testEmbeddedByValue()                      {}

// UnsafeURLGeneratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to URLGeneratorServer will
// result in compilation errors.
type UnsafeURLGeneratorServer interface {
	mustEmbedUnimplementedURLGeneratorServer()
}

func RegisterURLGeneratorServer(s grpc.ServiceRegistrar, srv URLGeneratorServer) {
	// If the following call pancis, it indicates UnimplementedURLGeneratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&URLGenerator_ServiceDesc, srv)
}

func _URLGenerator_GenerateShortURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLGeneratorServer).GenerateShortURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: URLGenerator_GenerateShortURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLGeneratorServer).GenerateShortURL(ctx, req.(*ShortURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _URLGenerator_DeleteShortURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteShortURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLGeneratorServer).DeleteShortURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: URLGenerator_DeleteShortURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLGeneratorServer).DeleteShortURL(ctx, req.(*DeleteShortURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _URLGenerator_GetAllURLs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLGeneratorServer).GetAllURLs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: URLGenerator_GetAllURLs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLGeneratorServer).GetAllURLs(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// URLGenerator_ServiceDesc is the grpc.ServiceDesc for URLGenerator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var URLGenerator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "URLGenerator",
	HandlerType: (*URLGeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateShortURL",
			Handler:    _URLGenerator_GenerateShortURL_Handler,
		},
		{
			MethodName: "DeleteShortURL",
			Handler:    _URLGenerator_DeleteShortURL_Handler,
		},
		{
			MethodName: "GetAllURLs",
			Handler:    _URLGenerator_GetAllURLs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "url-gen/proto/url-gen.proto",
}
