// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.23.4
// source: url-gen/proto/url-gen.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LongUrl       string                 `protobuf:"bytes,1,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	Expiration    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expiration,proto3" json:"expiration,omitempty"` // Optional expiration date
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortURLRequest) Reset() {
	*x = ShortURLRequest{}
	mi := &file_url_gen_proto_url_gen_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURLRequest) ProtoMessage() {}

func (x *ShortURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_gen_proto_url_gen_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortURLRequest.ProtoReflect.Descriptor instead.
func (*ShortURLRequest) Descriptor() ([]byte, []int) {
	return file_url_gen_proto_url_gen_proto_rawDescGZIP(), []int{0}
}

func (x *ShortURLRequest) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

func (x *ShortURLRequest) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

type ShortURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortURLResponse) Reset() {
	*x = ShortURLResponse{}
	mi := &file_url_gen_proto_url_gen_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURLResponse) ProtoMessage() {}

func (x *ShortURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_gen_proto_url_gen_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortURLResponse.ProtoReflect.Descriptor instead.
func (*ShortURLResponse) Descriptor() ([]byte, []int) {
	return file_url_gen_proto_url_gen_proto_rawDescGZIP(), []int{1}
}

func (x *ShortURLResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type DeleteShortURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrlCode  string                 `protobuf:"bytes,1,opt,name=short_url_code,json=shortUrlCode,proto3" json:"short_url_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShortURLRequest) Reset() {
	*x = DeleteShortURLRequest{}
	mi := &file_url_gen_proto_url_gen_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShortURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShortURLRequest) ProtoMessage() {}

func (x *DeleteShortURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_gen_proto_url_gen_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShortURLRequest.ProtoReflect.Descriptor instead.
func (*DeleteShortURLRequest) Descriptor() ([]byte, []int) {
	return file_url_gen_proto_url_gen_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteShortURLRequest) GetShortUrlCode() string {
	if x != nil {
		return x.ShortUrlCode
	}
	return ""
}

type DeleteShortURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Optional message for additional context
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShortURLResponse) Reset() {
	*x = DeleteShortURLResponse{}
	mi := &file_url_gen_proto_url_gen_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShortURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShortURLResponse) ProtoMessage() {}

func (x *DeleteShortURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_gen_proto_url_gen_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShortURLResponse.ProtoReflect.Descriptor instead.
func (*DeleteShortURLResponse) Descriptor() ([]byte, []int) {
	return file_url_gen_proto_url_gen_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteShortURLResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteShortURLResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_url_gen_proto_url_gen_proto protoreflect.FileDescriptor

const file_url_gen_proto_url_gen_proto_rawDesc = "" +
	"\n" +
	"\x1burl-gen/proto/url-gen.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"h\n" +
	"\x0fShortURLRequest\x12\x19\n" +
	"\blong_url\x18\x01 \x01(\tR\alongUrl\x12:\n" +
	"\n" +
	"expiration\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiration\"/\n" +
	"\x10ShortURLResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\"=\n" +
	"\x15DeleteShortURLRequest\x12$\n" +
	"\x0eshort_url_code\x18\x01 \x01(\tR\fshortUrlCode\"L\n" +
	"\x16DeleteShortURLResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x8a\x01\n" +
	"\fURLGenerator\x127\n" +
	"\x10GenerateShortURL\x12\x10.ShortURLRequest\x1a\x11.ShortURLResponse\x12A\n" +
	"\x0eDeleteShortURL\x12\x16.DeleteShortURLRequest\x1a\x17.DeleteShortURLResponseB;Z9github.com/andreistefanciprian/urlshortener/url-gen/protob\x06proto3"

var (
	file_url_gen_proto_url_gen_proto_rawDescOnce sync.Once
	file_url_gen_proto_url_gen_proto_rawDescData []byte
)

func file_url_gen_proto_url_gen_proto_rawDescGZIP() []byte {
	file_url_gen_proto_url_gen_proto_rawDescOnce.Do(func() {
		file_url_gen_proto_url_gen_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_url_gen_proto_url_gen_proto_rawDesc), len(file_url_gen_proto_url_gen_proto_rawDesc)))
	})
	return file_url_gen_proto_url_gen_proto_rawDescData
}

var file_url_gen_proto_url_gen_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_url_gen_proto_url_gen_proto_goTypes = []any{
	(*ShortURLRequest)(nil),        // 0: ShortURLRequest
	(*ShortURLResponse)(nil),       // 1: ShortURLResponse
	(*DeleteShortURLRequest)(nil),  // 2: DeleteShortURLRequest
	(*DeleteShortURLResponse)(nil), // 3: DeleteShortURLResponse
	(*timestamppb.Timestamp)(nil),  // 4: google.protobuf.Timestamp
}
var file_url_gen_proto_url_gen_proto_depIdxs = []int32{
	4, // 0: ShortURLRequest.expiration:type_name -> google.protobuf.Timestamp
	0, // 1: URLGenerator.GenerateShortURL:input_type -> ShortURLRequest
	2, // 2: URLGenerator.DeleteShortURL:input_type -> DeleteShortURLRequest
	1, // 3: URLGenerator.GenerateShortURL:output_type -> ShortURLResponse
	3, // 4: URLGenerator.DeleteShortURL:output_type -> DeleteShortURLResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_url_gen_proto_url_gen_proto_init() }
func file_url_gen_proto_url_gen_proto_init() {
	if File_url_gen_proto_url_gen_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_url_gen_proto_url_gen_proto_rawDesc), len(file_url_gen_proto_url_gen_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_url_gen_proto_url_gen_proto_goTypes,
		DependencyIndexes: file_url_gen_proto_url_gen_proto_depIdxs,
		MessageInfos:      file_url_gen_proto_url_gen_proto_msgTypes,
	}.Build()
	File_url_gen_proto_url_gen_proto = out.File
	file_url_gen_proto_url_gen_proto_goTypes = nil
	file_url_gen_proto_url_gen_proto_depIdxs = nil
}
