apiVersion: v1
kind: Secret
metadata:
  name: {{ include "url-read.fullname" . }}-secret
  labels:
    {{- include "url-read.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}