// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.23.4
// source: url-read/proto/url-read.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LongURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LongURLRequest) Reset() {
	*x = LongURLRequest{}
	mi := &file_url_read_proto_url_read_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LongURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LongURLRequest) ProtoMessage() {}

func (x *LongURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_read_proto_url_read_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LongURLRequest.ProtoReflect.Descriptor instead.
func (*LongURLRequest) Descriptor() ([]byte, []int) {
	return file_url_read_proto_url_read_proto_rawDescGZIP(), []int{0}
}

func (x *LongURLRequest) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type LongURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LongUrl       string                 `protobuf:"bytes,1,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	Expiration    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expiration,proto3" json:"expiration,omitempty"` // Optional expiration date
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LongURLResponse) Reset() {
	*x = LongURLResponse{}
	mi := &file_url_read_proto_url_read_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LongURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LongURLResponse) ProtoMessage() {}

func (x *LongURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_read_proto_url_read_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LongURLResponse.ProtoReflect.Descriptor instead.
func (*LongURLResponse) Descriptor() ([]byte, []int) {
	return file_url_read_proto_url_read_proto_rawDescGZIP(), []int{1}
}

func (x *LongURLResponse) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

func (x *LongURLResponse) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

var File_url_read_proto_url_read_proto protoreflect.FileDescriptor

const file_url_read_proto_url_read_proto_rawDesc = "" +
	"\n" +
	"\x1durl-read/proto/url-read.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"-\n" +
	"\x0eLongURLRequest\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\"h\n" +
	"\x0fLongURLResponse\x12\x19\n" +
	"\blong_url\x18\x01 \x01(\tR\alongUrl\x12:\n" +
	"\n" +
	"expiration\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiration2<\n" +
	"\tURLReader\x12/\n" +
	"\n" +
	"GetLongURL\x12\x0f.LongURLRequest\x1a\x10.LongURLResponseB<Z:github.com/andreistefanciprian/urlshortener/url-read/protob\x06proto3"

var (
	file_url_read_proto_url_read_proto_rawDescOnce sync.Once
	file_url_read_proto_url_read_proto_rawDescData []byte
)

func file_url_read_proto_url_read_proto_rawDescGZIP() []byte {
	file_url_read_proto_url_read_proto_rawDescOnce.Do(func() {
		file_url_read_proto_url_read_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_url_read_proto_url_read_proto_rawDesc), len(file_url_read_proto_url_read_proto_rawDesc)))
	})
	return file_url_read_proto_url_read_proto_rawDescData
}

var file_url_read_proto_url_read_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_url_read_proto_url_read_proto_goTypes = []any{
	(*LongURLRequest)(nil),        // 0: LongURLRequest
	(*LongURLResponse)(nil),       // 1: LongURLResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_url_read_proto_url_read_proto_depIdxs = []int32{
	2, // 0: LongURLResponse.expiration:type_name -> google.protobuf.Timestamp
	0, // 1: URLReader.GetLongURL:input_type -> LongURLRequest
	1, // 2: URLReader.GetLongURL:output_type -> LongURLResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_url_read_proto_url_read_proto_init() }
func file_url_read_proto_url_read_proto_init() {
	if File_url_read_proto_url_read_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_url_read_proto_url_read_proto_rawDesc), len(file_url_read_proto_url_read_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_url_read_proto_url_read_proto_goTypes,
		DependencyIndexes: file_url_read_proto_url_read_proto_depIdxs,
		MessageInfos:      file_url_read_proto_url_read_proto_msgTypes,
	}.Build()
	File_url_read_proto_url_read_proto = out.File
	file_url_read_proto_url_read_proto_goTypes = nil
	file_url_read_proto_url_read_proto_depIdxs = nil
}
