// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.23.4
// source: url-read/proto/url-read.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	URLReader_GetLongURL_FullMethodName = "/URLReader/GetLongURL"
)

// URLReaderClient is the client API for URLReader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type URLReaderClient interface {
	GetLongURL(ctx context.Context, in *LongURLRequest, opts ...grpc.CallOption) (*LongURLResponse, error)
}

type uRLReaderClient struct {
	cc grpc.ClientConnInterface
}

func NewURLReaderClient(cc grpc.ClientConnInterface) URLReaderClient {
	return &uRLReaderClient{cc}
}

func (c *uRLReaderClient) GetLongURL(ctx context.Context, in *LongURLRequest, opts ...grpc.CallOption) (*LongURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LongURLResponse)
	err := c.cc.Invoke(ctx, URLReader_GetLongURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// URLReaderServer is the server API for URLReader service.
// All implementations must embed UnimplementedURLReaderServer
// for forward compatibility.
type URLReaderServer interface {
	GetLongURL(context.Context, *LongURLRequest) (*LongURLResponse, error)
	mustEmbedUnimplementedURLReaderServer()
}

// UnimplementedURLReaderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedURLReaderServer struct{}

func (UnimplementedURLReaderServer) GetLongURL(context.Context, *LongURLRequest) (*LongURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLongURL not implemented")
}
func (UnimplementedURLReaderServer) mustEmbedUnimplementedURLReaderServer() {}
func (UnimplementedURLReaderServer) testEmbeddedByValue()                   {}

// UnsafeURLReaderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to URLReaderServer will
// result in compilation errors.
type UnsafeURLReaderServer interface {
	mustEmbedUnimplementedURLReaderServer()
}

func RegisterURLReaderServer(s grpc.ServiceRegistrar, srv URLReaderServer) {
	// If the following call pancis, it indicates UnimplementedURLReaderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&URLReader_ServiceDesc, srv)
}

func _URLReader_GetLongURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LongURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLReaderServer).GetLongURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: URLReader_GetLongURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLReaderServer).GetLongURL(ctx, req.(*LongURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// URLReader_ServiceDesc is the grpc.ServiceDesc for URLReader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var URLReader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "URLReader",
	HandlerType: (*URLReaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLongURL",
			Handler:    _URLReader_GetLongURL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "url-read/proto/url-read.proto",
}
