apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd-image-updater.argoproj.io/image-list: andreistefanciprian/urlshortener-api-gateway
    argocd-image-updater.argoproj.io/update-strategy: digest
    argocd-image-updater.argoproj.io/pull-policy: Always
    argocd-image-updater.argoproj.io/helm.image-name: image.repository
    argocd-image-updater.argoproj.io/helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/helm.image-digest: image.digest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:git-creds
    argocd-image-updater.argoproj.io/pull-request: "true"
    argocd-image-updater.argoproj.io/pull-request.target-branch: main
    argocd-image-updater.argoproj.io/git-branch: image-updater-{{.SHA256}}
    
spec:
  project: urlshortener
  sources:
    - repoURL: oci://ghcr.io/andreistefanciprian/urlshortener/api-gateway
      chart: api-gateway
      targetRevision: 0.1.11
      helm:
        valueFiles:
          - $values/k8s/values/api-gateway.values.yaml
        ignoreMissingValueFiles: false
    - repoURL: https://github.com/andreistefanciprian/urlshortener.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: api-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
