apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: urlshortener
  source:
    repoURL: oci://ghcr.io/andreistefanciprian/urlshortener/api-gateway
    chart: api-gateway
    # Set to the exact chart version you want to deploy (example below).
    targetRevision: 0.1.10
    helm:
      # Optional overrides to the chart's values.yaml
      values: |
        image:
repository: docker.io/andreistefanciprian/urlshortener-api-gateway
digest: sha256:d0d7f207a63eaec6af752b4fe769b15cd8391e8cb01ff457e5c458f96cdb0d57
        config:
          LOG_LEVEL: DEBUG
          URL_GEN_HOST: url-gen.url-gen.svc
          URL_GEN_PORT: "50052"
          URL_READ_HOST: url-read.url-read.svc
          URL_READ_PORT: "50053"
          API_GATEWAY_PORT: "8080"
          METRICS_PORT: "9090"
  destination:
    server: https://kubernetes.default.svc
    namespace: api-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
