apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: urlshortener
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.14.0
    chart: argocd-image-updater
    helm:
      values: |
        rbac:
          create: true
        serviceAccount:
          create: true
        config:
          logLevel: info
          registries:
            - name: Docker Hub
              api_url: https://registry-1.docker.io
              prefix: docker.io
              default: true
              ping: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
