apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd-image-updater.argoproj.io/image-list: frontend=andreistefanciprian/urlshortener-frontend
    argocd-image-updater.argoproj.io/frontend.update-strategy: digest
    argocd-image-updater.argoproj.io/frontend.helm.parameters: "-p image.repository=%(image) -p image.digest=%(digest)"
spec:
  project: urlshortener
  sources:
    - repoURL: oci://ghcr.io/andreistefanciprian/urlshortener/frontend
      chart: frontend
      targetRevision: 0.1.2
      helm:
        valueFiles:
          - $values/frontend.values.yaml
    - repoURL: https://github.com/andreistefanciprian/urlshortener.git
      targetRevision: main
      ref: values
      path: k8s/values
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
