apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: url-read
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    # Removed Argo CD Image Updater annotations; Renovate will manage image digests
spec:
  project: urlshortener
  source:
    repoURL: oci://ghcr.io/andreistefanciprian/urlshortener/url-read
    chart: url-read
    targetRevision: 0.1.9
    helm:
      values: |
        image:
          repository: andreistefanciprian/urlshortener-url-read
          tag: latest@sha256:2dc3ab45c5760b0028cfb5f3f5761424aa1875f56426d47b872ef9a4dafe6fc2
        config:
          LOG_LEVEL: DEBUG
          DB_HOST: postgres-postgresql.postgres.svc
          REDIS_HOST: redis-master.redis.svc
          DB_USER: url_gen_user
          REDIS_DB: "0"
  destination:
    server: https://kubernetes.default.svc
    namespace: url-read
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
