apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: url-gen
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd-image-updater.argoproj.io/image-list: andreistefanciprian/urlshortener-url-gen:latest
    argocd-image-updater.argoproj.io/update-strategy: digest
    argocd-image-updater.argoproj.io/helm.image-name: image.repository
    argocd-image-updater.argoproj.io/helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/helm.image-digest: image.digest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-repository: https://github.com/andreistefanciprian/urlshortener.git
    argocd-image-updater.argoproj.io/pull-request: "true"
    argocd-image-updater.argoproj.io/pull-request.target-branch: main
    argocd-image-updater.argoproj.io/git-commit-message: "chore(url-gen): update image to {{new_tag}} ({{new_digest}})"
spec:
  project: urlshortener
  sources:
    - repoURL: oci://ghcr.io/andreistefanciprian/urlshortener/url-gen
      chart: url-gen
      targetRevision: 0.1.7
      helm:
        valueFiles:
          - $values/k8s/values/url-gen.values.yaml
        ignoreMissingValueFiles: false
    - repoURL: https://github.com/andreistefanciprian/urlshortener.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: url-gen
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
