name: url-gen container image build and push to DockerHub

on:
  push:
    tags:
      - '*'
    branches:
      - 'main'
    paths:
      - 'url-gen/go.*'
      - 'url-gen/**/*.go'
      - 'url-gen/infra/Dockerfile'
      - '.github/workflows/docker-url-gen.yaml'
  pull_request:
    branches: [ 'main' ]
    paths:
      - 'url-gen/go.*'
      - 'url-gen/**/*.go'
      - 'url-gen/infra/Dockerfile'
      - '.github/workflows/docker-url-gen.yaml'
  workflow_dispatch:
  
permissions:
  contents: read
  id-token: write
  attestations: write
  
jobs:

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('url-gen/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        working-directory: ./url-gen
        run: go mod download

      - name: Run integration unit tests
        working-directory: ./url-gen
        run: go test -v ./internal/implementation/

  generate-build-id:
    needs: [unit-tests]
    runs-on: ubuntu-latest
    outputs:
      BUILD_ID: ${{ steps.prep.outputs.BUILD_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Generate build ID
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "BUILD_ID=${branch}-${sha}-${ts}" >> $GITHUB_OUTPUT

  docker:
    needs: [generate-build-id]
    uses: andreistefanciprian/gh-reusable-workflows/.github/workflows/build_and_push_docker_image_to_dockerhub.yaml@main
    with:
      image_name: andreistefanciprian/urlshortener-url-gen
      image_tag: ${{ needs.generate-build-id.outputs.BUILD_ID }}
      dockerhub_username: andreistefanciprian
      file: url-gen/infra/Dockerfile
      context: ./url-gen
    secrets: inherit