name: Demo - Build & Push to GHCR

on:
  push:
    tags:
      - 'demo-v*'
    branches:
      - 'main'
    paths:
      - 'demo/go.*'
      - 'demo/**/*.go'
      - 'demo/infra/Dockerfile'
      - '.github/workflows/ghcr-demo.yaml'
      - 'demo/version.txt'
      - 'demo/CHANGELOG.md'

  pull_request:
    branches:
      - 'main'
    paths:
      - 'demo/go.*'
      - 'demo/**/*.go'
      - 'demo/infra/Dockerfile'
      - '.github/workflows/ghcr-demo.yaml'

  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  attestations: write
  packages: write

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.26.1'
          cache-dependency-path: demo/go.sum

      - name: Install dependencies
        working-directory: ./demo
        run: go mod download

      - name: Run go vet
        working-directory: ./demo
        run: go vet ./cmd/...

      - name: Run gofmt
        working-directory: ./demo
        run: test -z "$(gofmt -l .)"

  generate-build-id:
    needs: [unit-tests]
    runs-on: ubuntu-latest
    outputs:
      BUILD_ID: ${{ steps.prep.outputs.BUILD_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Generate build ID
        id: prep
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            echo "BUILD_ID=${GITHUB_REF_NAME#demo-v}" >> $GITHUB_OUTPUT
          elif [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
            pr_number=${GITHUB_REF_NAME%/merge}
            sha=${GITHUB_SHA::8}
            echo "BUILD_ID=pr-${pr_number}-${sha}" >> $GITHUB_OUTPUT
          else
            branch=${GITHUB_REF##*/}
            sha=${GITHUB_SHA::8}
            ts=$(date +%s)
            echo "BUILD_ID=${branch}-${sha}-${ts}" >> $GITHUB_OUTPUT
          fi

      - name: Print build ID
        run: |
          echo "BUILD_ID: ${{ steps.prep.outputs.BUILD_ID }}"

  docker:
    needs: [generate-build-id]
    uses: andreistefanciprian/gh-reusable-workflows/.github/workflows/build_and_push_docker_image_to_ghcr.yaml@main
    with:
      image_name: ghcr.io/andreistefanciprian/demo
      image_tag: ${{ needs.generate-build-id.outputs.BUILD_ID }}
      file: demo/infra/Dockerfile
      context: ./demo
      push_latest: ${{ github.ref == 'refs/heads/main' }}
      trivy_scan: true
      trivy_scan_severity: CRITICAL,HIGH
      trivy_ignore_unfixed: true
      cosign_sign: true
      cosign_attest_sbom: true
    secrets: inherit
